<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>EmacsWiki: icicles.el</title><link rel="alternate" type="application/wiki" title="Edit this page" href="http://www.emacswiki.org/emacs?action=edit;id=icicles.el" /><link type="text/css" rel="stylesheet" href="/emacs/wiki.css" /><meta name="robots" content="INDEX,FOLLOW" /><link rel="alternate" type="application/rss+xml" title="EmacsWiki" href="http://www.emacswiki.org/emacs?action=rss" /><link rel="alternate" type="application/rss+xml" title="EmacsWiki: icicles.el" href="http://www.emacswiki.org/emacs?action=rss;rcidonly=icicles.el" />
<link rel="alternate" type="application/rss+xml"
      title="Emacs Wiki with page content"
      href="http://www.emacswiki.org/emacs/full.rss" />
<link rel="alternate" type="application/rss+xml"
      title="Emacs Wiki with page content and diff"
      href="http://www.emacswiki.org/emacs/full-diff.rss" />
<link rel="alternate" type="application/rss+xml"
      title="Emacs Wiki including minor differences"
      href="http://www.emacswiki.org/emacs/minor-edits.rss" />
<link rel="alternate" type="application/rss+xml"
      title="Changes for icicles.el only"
      href="http://www.emacswiki.org/emacs?action=rss;rcidonly=icicles.el" /><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/></head><body class="http://www.emacswiki.org/emacs"><div class="header"><a class="logo" href="http://www.emacswiki.org/emacs/SiteMap"><img class="logo" src="/emacs_logo.png" alt="[Home]" /></a><span class="gotobar bar"><a class="local" href="http://www.emacswiki.org/emacs/SiteMap">SiteMap</a> <a class="local" href="http://www.emacswiki.org/emacs/Search">Search</a> <a class="local" href="http://www.emacswiki.org/emacs/ElispArea">ElispArea</a> <a class="local" href="http://www.emacswiki.org/emacs/HowTo">HowTo</a> <a class="local" href="http://www.emacswiki.org/emacs/RecentChanges">RecentChanges</a> <a class="local" href="http://www.emacswiki.org/emacs/News">News</a> <a class="local" href="http://www.emacswiki.org/emacs/Problems">Problems</a> <a class="local" href="http://www.emacswiki.org/emacs/Suggestions">Suggestions</a> </span>
<!-- Google CSE Search Box Begins  -->
<form class="tiny" action="http://www.google.com/cse" id="searchbox_004774160799092323420:6-ff2s0o6yi"><p>
<input type="hidden" name="cx" value="004774160799092323420:6-ff2s0o6yi" />
<input type="text" name="q" size="25" />
<input type="submit" name="sa" value="Search" />
</p></form>
<script type="text/javascript" src="http://www.google.com/coop/cse/brand?form=searchbox_004774160799092323420%3A6-ff2s0o6yi"></script>
<!-- Google CSE Search Box Ends -->
<h1><a title="Click to search for references to this page" rel="nofollow" href="http://www.google.com/cse?cx=004774160799092323420:6-ff2s0o6yi&amp;q=%22icicles.el%22">icicles.el</a></h1></div><div class="wrapper"><div class="content browse"><p><a href="http://www.emacswiki.org/emacs/download/icicles.el">Download</a></p><pre class="code"><span class="linecomment">;;; icicles.el --- Minibuffer input completion and cycling.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;; Filename: icicles.el</span>
<span class="linecomment">;; Description: Minibuffer completion and cycling.</span>
<span class="linecomment">;; Author: Drew Adams</span>
<span class="linecomment">;; Maintainer: Drew Adams</span>
<span class="linecomment">;; Copyright (C) 1996-2009, Drew Adams, all rights reserved.</span>
<span class="linecomment">;; Created: Tue Aug  1 14:21:16 1995</span>
<span class="linecomment">;; Version: 22.0</span>
<span class="linecomment">;; Last-Updated: Mon Feb 23 16:23:07 2009 (-0800)</span>
<span class="linecomment">;;           By: dradams</span>
<span class="linecomment">;;     Update #: 22397</span>
<span class="linecomment">;; URL: http://www.emacswiki.org/cgi-bin/wiki/icicles.el</span>
<span class="linecomment">;; Keywords: internal, extensions, help, abbrev, local, minibuffer,</span>
<span class="linecomment">;;           keys, apropos, completion, matching, regexp, command</span>
<span class="linecomment">;; Compatibility: GNU Emacs 20.x, GNU Emacs 21.x, GNU Emacs 22.x</span>
<span class="linecomment">;;</span>
<span class="linecomment">;; Features that might be required by this library:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;   `apropos', `apropos+', `apropos-fn+var', `avoid', `cl',</span>
<span class="linecomment">;;   `color-theme', `cus-edit', `cus-face', `cus-load', `cus-start',</span>
<span class="linecomment">;;   `custom', `dired', `dired+', `dired-aux', `dired-x', `doremi',</span>
<span class="linecomment">;;   `easymenu', `ediff-diff', `ediff-help', `ediff-init',</span>
<span class="linecomment">;;   `ediff-merg', `ediff-mult', `ediff-util', `ediff-wind', `ffap',</span>
<span class="linecomment">;;   `ffap-', `fit-frame', `frame-cmds', `frame-fns', `help+20',</span>
<span class="linecomment">;;   `hexrgb', `icicles-cmd', `icicles-face', `icicles-fn',</span>
<span class="linecomment">;;   `icicles-mac', `icicles-mcmd', `icicles-mode', `icicles-opt',</span>
<span class="linecomment">;;   `icicles-var', `info', `info+', `kmacro', `levenshtein',</span>
<span class="linecomment">;;   `menu-bar', `menu-bar+', `misc-cmds', `misc-fns', `mkhtml',</span>
<span class="linecomment">;;   `mkhtml-htmlize', `mwheel', `pp', `pp+', `ring', `ring+',</span>
<span class="linecomment">;;   `second-sel', `strings', `subr-21', `thingatpt', `thingatpt+',</span>
<span class="linecomment">;;   `unaccent', `w32-browser', `w32browser-dlgopen', `wid-edit',</span>
<span class="linecomment">;;   `wid-edit+', `widget'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;; Commentary:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Minibuffer input completion and cycling of completion candidates.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Input completion takes as input a string and returns a name that</span>
<span class="linecomment">;;  contains the input string.  This library enables minibuffer</span>
<span class="linecomment">;;  cycling of completion candidates, and provides additional support</span>
<span class="linecomment">;;  for input completion.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Two kinds of completion are offered here, which are distinguished</span>
<span class="linecomment">;;  by how the input string is matched against the completed name:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;   - Prefix completion - The input string is a prefix of the</span>
<span class="linecomment">;;                         completed name.  This is the usual Emacs</span>
<span class="linecomment">;;                         completion.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;   - Apropos completion - The input string is a regular expression</span>
<span class="linecomment">;;                          that matches somewhere (anywhere) within</span>
<span class="linecomment">;;                          the completed name.  You can think of the</span>
<span class="linecomment">;;                          name as having been returned by `apropos'</span>
<span class="linecomment">;;                          (except it also works for file and buffer</span>
<span class="linecomment">;;                          names).</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Files `icicles-doc1.el' and `icicles-doc2.el' contain the doc for</span>
<span class="linecomment">;;  Icicles, including how to install and use Icicles.  You can also</span>
<span class="linecomment">;;  read the Icicles doc, in formatted form, on the Emacs-Wiki Web</span>
<span class="linecomment">;;  site: http://www.emacswiki.org/cgi-bin/wiki/Icicles.  Emacs Wiki</span>
<span class="linecomment">;;  also has a few addtional pages about Icicles.  In particular, if</span>
<span class="linecomment">;;  you are new to Emacs, as well as Icicles, see this page:</span>
<span class="linecomment">;;  http://www.emacswiki.org/cgi-bin/wiki/EmacsNewbieWithIcicles.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  See also: Library `lacarte.el', which lets you execute menu</span>
<span class="linecomment">;;  commands, cycling and completing them.  It is not part of Icicles,</span>
<span class="linecomment">;;  but it is greatly enhanced by Icicles.</span>
 
<span class="linecomment">;;(@&gt; "Index")</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Index</span>
<span class="linecomment">;;  -----</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  If you have library `linkd.el' and Emacs 22 or later, load</span>
<span class="linecomment">;;  `linkd.el' and turn on `linkd-mode' now.  It lets you easily</span>
<span class="linecomment">;;  navigate around the sections of this doc.  Linkd mode will</span>
<span class="linecomment">;;  highlight this Index, as well as the cross-references and section</span>
<span class="linecomment">;;  headings throughout this file.  You can get `linkd.el' here:</span>
<span class="linecomment">;;  http://dto.freeshell.org/notebook/Linkd.html.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  (@&gt; "Things Defined in Icicles")</span>
 
<span class="linecomment">;;(@* "Things Defined in Icicles")</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Things Defined in Icicles</span>
<span class="linecomment">;;  -------------------------</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Key bindings defined in Icicles: see (@&gt; "Key Bindings"), below.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Macros defined in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;    `icicle-define-add-to-alist-command', `icicle-define-command',</span>
<span class="linecomment">;;    `icicle-define-file-command', `icicle-define-sort-command'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Commands defined in Icicles -</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;   Commands to be used mainly at top level:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;    `a', `any', `buffer', `clear-option', `file',</span>
<span class="linecomment">;;    `icicle-add-buffer-candidate', `icicle-add-buffer-config',</span>
<span class="linecomment">;;    `icicle-add-entry-to-saved-completion-set',</span>
<span class="linecomment">;;    `icicle-add-file-to-fileset', `icicle-add-region',</span>
<span class="linecomment">;;    `icicle-add/update-saved-completion-set', `icicle-anything',</span>
<span class="linecomment">;;    `icicle-apply' `icicle-apropos', `icicle-apropos-command',</span>
<span class="linecomment">;;    `icicle-apropos-function', `icicle-apropos-option',</span>
<span class="linecomment">;;    `icicle-apropos-variable', `icicle-apropos-zippy',</span>
<span class="linecomment">;;    `icicle-bbdb-complete-name', `icicle-bookmark',</span>
<span class="linecomment">;;    `icicle-bookmark-cmd', `icicle-bookmark-jump',</span>
<span class="linecomment">;;    `icicle-bookmark-jump-other-window',</span>
<span class="linecomment">;;    `icicle-bookmark-other-window', `icicle-buffer',</span>
<span class="linecomment">;;    `icicle-buffer-config', `icicle-buffer-list',</span>
<span class="linecomment">;;    `icicle-buffer-other-window',</span>
<span class="linecomment">;;    `icicle-change-alternative-sort-order',</span>
<span class="linecomment">;;    `icicle-change-sort-order', `icicle-clear-history',</span>
<span class="linecomment">;;    `icicle-clear-current-history', `icicle-color-theme',</span>
<span class="linecomment">;;    `icicle-comint-command', `icicle-comint-dynamic-complete',</span>
<span class="linecomment">;;    `icicle-comint-dynamic-complete-filename',</span>
<span class="linecomment">;;    `icicle-comint-replace-by-expanded-filename',</span>
<span class="linecomment">;;    `icicle-comint-search', `icicle-command-abbrev',</span>
<span class="linecomment">;;    `icicle-compilation-search', `icicle-complete-keys',</span>
<span class="linecomment">;;    `icicle-complete-thesaurus-entry', `icicle-completing-yank',</span>
<span class="linecomment">;;    `icicle-customize-apropos', `icicle-customize-apropos-faces',</span>
<span class="linecomment">;;    `icicle-customize-apropos-groups',</span>
<span class="linecomment">;;    `icicle-customize-apropos-options',</span>
<span class="linecomment">;;    `icicle-customize-apropos-options-of-type',</span>
<span class="linecomment">;;    `icicle-customize-face', `icicle-customize-icicles-group',</span>
<span class="linecomment">;;    `icicle-dabbrev-completion', `icicle-delete-file',</span>
<span class="linecomment">;;    `icicle-delete-window', `icicle-delete-windows',</span>
<span class="linecomment">;;    `icicle-delete-windows-on', `icicle-describe-file',</span>
<span class="linecomment">;;    `icicle-describe-option-of-type', `icicle-directory-list',</span>
<span class="linecomment">;;    `icicle-dired-chosen-files',</span>
<span class="linecomment">;;    `icicle-dired-chosen-files-other-window',</span>
<span class="linecomment">;;    `icicle-dired-project', `icicle-dired-project-other-window',</span>
<span class="linecomment">;;    `icicle-dired-saved-file-candidates',</span>
<span class="linecomment">;;    `icicle-dired-saved-file-candidates-other-window',</span>
<span class="linecomment">;;    `icicle-dired-save-marked',</span>
<span class="linecomment">;;    `icicle-dired-save-marked-as-project',</span>
<span class="linecomment">;;    `icicle-dired-save-marked-more',</span>
<span class="linecomment">;;    `icicle-dired-save-marked-persistently',</span>
<span class="linecomment">;;    `icicle-dired-save-marked-to-variable', `icicle-doc',</span>
<span class="linecomment">;;    `icicle-ess-complete-filename',</span>
<span class="linecomment">;;    `icicle-ess-complete-object-name',</span>
<span class="linecomment">;;    `icicle-ess-internal-complete-object-name',</span>
<span class="linecomment">;;    `icicle-ess-R-complete-object-name',</span>
<span class="linecomment">;;    `icicle-exchange-point-and-mark',</span>
<span class="linecomment">;;    `icicle-execute-extended-command',</span>
<span class="linecomment">;;    `icicle-execute-named-keyboard-macro', `icicle-face-list',</span>
<span class="linecomment">;;    `icicle-file', `icicle-file-list', `icicle-file-other-window',</span>
<span class="linecomment">;;    `icicle-find-file', `icicle-find-file-absolute',</span>
<span class="linecomment">;;    `icicle-find-file-absolute-other-window',</span>
<span class="linecomment">;;    `icicle-find-file-other-window', `icicle-find-tag',</span>
<span class="linecomment">;;    `icicle-font', `icicle-frame-bg', `icicle-frame-fg',</span>
<span class="linecomment">;;    `icicle-fundoc', `icicle-goto-global-marker',</span>
<span class="linecomment">;;    `icicle-goto-global-marker-or-pop-global-mark',</span>
<span class="linecomment">;;    `icicle-goto-marker', `icicle-goto-marker-or-set-mark-command',</span>
<span class="linecomment">;;    `icicle-grep-saved-file-candidates',</span>
<span class="linecomment">;;    `icicle-gud-gdb-complete-command', `icicle-handle-switch-frame',</span>
<span class="linecomment">;;    `icicle-imenu', `icicle-imenu-command',</span>
<span class="linecomment">;;    `icicle-imenu-non-interactive-function',</span>
<span class="linecomment">;;    `icicle-Info-goto-node', `icicle-Info-goto-node-cmd',</span>
<span class="linecomment">;;    `icicle-Info-index', `icicle-Info-index-20',</span>
<span class="linecomment">;;    `icicle-Info-index-cmd', `icicle-Info-menu',</span>
<span class="linecomment">;;    `icicle-Info-menu-cmd', `icicle-insert-char',</span>
<span class="linecomment">;;    `icicle-insert-thesaurus-entry', `icicle-keyword-list',</span>
<span class="linecomment">;;    `icicle-kill-buffer', `icicle-kmacro',</span>
<span class="linecomment">;;    `icicle-lisp-complete-symbol', `icicle-locate-file',</span>
<span class="linecomment">;;    `icicle-locate-file-other-window', `icicle-mode', `icy-mode',</span>
<span class="linecomment">;;    `icicle-object-action', `icicle-occur',</span>
<span class="linecomment">;;    `icicle-other-window-or-frame', `icicle-plist',</span>
<span class="linecomment">;;    `icicle-pop-tag-mark', `icicle-pp-eval-expression',</span>
<span class="linecomment">;;    `icicle-read-color', `icicle-read-kbd-macro',</span>
<span class="linecomment">;;    `icicle-recent-file', `icicle-recent-file-other-window',</span>
<span class="linecomment">;;    `icicle-regexp-list', `icicle-region-open-all-files',</span>
<span class="linecomment">;;    `icicle-remove-all-regions-in-buffer',</span>
<span class="linecomment">;;    `icicle-remove-buffer-candidate', `icicle-remove-buffer-config',</span>
<span class="linecomment">;;    `icicle-remove-entry-from-saved-completion-set',</span>
<span class="linecomment">;;    `icicle-remove-region', `icicle-remove-saved-completion-set',</span>
<span class="linecomment">;;    `icicle-repeat-complex-command', `icicle-reset-option-to-nil',</span>
<span class="linecomment">;;    `icicle-save-string-to-variable', `icicle-search',</span>
<span class="linecomment">;;    `icicle-search-all-regions', `icicle-search-buffer',</span>
<span class="linecomment">;;    `icicle-search-buff-menu-marked', `icicle-search-char-property',</span>
<span class="linecomment">;;    `icicle-search-dired-marked', `icicle-search-file',</span>
<span class="linecomment">;;    `icicle-search-generic', `icicle-search-highlight-cleanup',</span>
<span class="linecomment">;;    `icicle-search-ibuffer-marked', `icicle-search-keywords',</span>
<span class="linecomment">;;    `icicle-search-overlay-property', `icicle-search-region',</span>
<span class="linecomment">;;    `icicle-search-text-property', `icicle-search-word',</span>
<span class="linecomment">;;    `icicle-select-frame', `icicle-select-frame-by-name',</span>
<span class="linecomment">;;    `icicle-select-region', `icicle-select-window',</span>
<span class="linecomment">;;    `icicle-select-window-by-name', `icicle-send-bug-report',</span>
<span class="linecomment">;;    `icicle-set-option-to-t',</span>
<span class="linecomment">;;    `icicle-shell-dynamic-complete-command',</span>
<span class="linecomment">;;    `icicle-shell-dynamic-complete-environment-variable',</span>
<span class="linecomment">;;    `icicle-shell-dynamic-complete-filename',</span>
<span class="linecomment">;;    `icicle-skip-this-command', `icicle-sort-alphabetical',</span>
<span class="linecomment">;;    `icicle-sort-by-abbrev-frequency',</span>
<span class="linecomment">;;    `icicle-sort-by-directories-last',</span>
<span class="linecomment">;;    `icicle-sort-by-last-file-modification-time',</span>
<span class="linecomment">;;    `icicle-sort-by-last-use',</span>
<span class="linecomment">;;    `icicle-sort-by-previous-use-alphabetically',</span>
<span class="linecomment">;;    `icicle-sort-by-2nd-parts-alphabetically',</span>
<span class="linecomment">;;    `icicle-sort-case-insensitive',</span>
<span class="linecomment">;;    `icicle-sort-extra-candidates-first',</span>
<span class="linecomment">;;    `icicle-sort-proxy-candidates-first',</span>
<span class="linecomment">;;    `icicle-sort-special-candidates-first',</span>
<span class="linecomment">;;    `icicle-sort-special-candidates-first',</span>
<span class="linecomment">;;    `icicle-sort-turned-OFF', `icicle-tags-search',</span>
<span class="linecomment">;;    `icicle-toggle-~-for-home-dir',</span>
<span class="linecomment">;;    `icicle-toggle-alternative-sorting',</span>
<span class="linecomment">;;    `icicle-toggle-angle-brackets',</span>
<span class="linecomment">;;    `icicle-toggle-apropos-match-function',</span>
<span class="linecomment">;;    `icicle-toggle-case-sensitivity', `icicle-toggle-C-for-actions',</span>
<span class="linecomment">;;    `icicle-toggle-fuzzy-completion',</span>
<span class="linecomment">;;    `icicle-toggle-hiding-common-match',</span>
<span class="linecomment">;;    `icicle-toggle-highlight-all-current',</span>
<span class="linecomment">;;    `icicle-toggle-highlight-historical-candidates',</span>
<span class="linecomment">;;    `icicle-toggle-ignored-extensions',</span>
<span class="linecomment">;;    `icicle-toggle-ignored-space-prefix',</span>
<span class="linecomment">;;    `icicle-toggle-incremental-completion',</span>
<span class="linecomment">;;    `icicle-toggle-literal-replacement', `icicle-toggle-option',</span>
<span class="linecomment">;;    `icicle-toggle-proxy-candidates', `icicle-toggle-regexp-quote',</span>
<span class="linecomment">;;    `icicle-toggle-remote-file-testing',</span>
<span class="linecomment">;;    `icicle-toggle-search-cleanup',</span>
<span class="linecomment">;;    `icicle-toggle-search-replace-whole',</span>
<span class="linecomment">;;    `icicle-toggle-search-whole-word', `icicle-toggle-sorting',</span>
<span class="linecomment">;;    `icicle-toggle-transforming',</span>
<span class="linecomment">;;    `icicle-toggle-WYSIWYG-Completions', `icicle-vardoc',</span>
<span class="linecomment">;;    `icicle-where-is', `icicle-yank-maybe-completing',</span>
<span class="linecomment">;;    `old-bbdb-complete-name', `old-comint-dynamic-complete',</span>
<span class="linecomment">;;    `old-comint-replace-by-expanded-filename',</span>
<span class="linecomment">;;    `old-dired-read-shell-command', `old-ess-complete-object-name',</span>
<span class="linecomment">;;    `old-gud-gdb-complete-command', `old-read-shell-command',</span>
<span class="linecomment">;;    `orig-read-file-name', `toggle', `toggle-icicle-~-for-home-dir',</span>
<span class="linecomment">;;    `toggle-icicle-alternative-sorting',</span>
<span class="linecomment">;;    `toggle-icicle-angle-brackets',</span>
<span class="linecomment">;;    `toggle-icicle-apropos-match-function',</span>
<span class="linecomment">;;    `toggle-icicle-case-sensitivity', `toggle-icicle-C-for-actions',</span>
<span class="linecomment">;;    `toggle-icicle-fuzzy-completion',</span>
<span class="linecomment">;;    `toggle-icicle-highlight-all-current',</span>
<span class="linecomment">;;    `toggle-icicle-highlight-historical-candidates',</span>
<span class="linecomment">;;    `toggle-icicle-ignored-extensions',</span>
<span class="linecomment">;;    `toggle-icicle-ignored-space-prefix',</span>
<span class="linecomment">;;    `toggle-icicle-incremental-completion',</span>
<span class="linecomment">;;    `toggle-icicle-literal-replacement',</span>
<span class="linecomment">;;    `toggle-icicle-proxy-candidates', `toggle-icicle-regexp-quote',</span>
<span class="linecomment">;;    `toggle-icicle-remote-file-testing',</span>
<span class="linecomment">;;    `toggle-icicle-search-cleanup',</span>
<span class="linecomment">;;    `toggle-icicle-search-replace-whole',</span>
<span class="linecomment">;;    `toggle-icicle-search-whole-word', `toggle-icicle-sorting',</span>
<span class="linecomment">;;    `toggle-icicle-transforming',</span>
<span class="linecomment">;;    `toggle-icicle-WYSIWYG-Completions', `what-which-how'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;   Commands to be used mainly in the minibuffer or *Completions*:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;    `icicle-abort-recursive-edit', `icicle-all-candidates-action',</span>
<span class="linecomment">;;    `icicle-all-candidates-alt-action',</span>
<span class="linecomment">;;    `icicle-all-candidates-list-action',</span>
<span class="linecomment">;;    `icicle-all-candidates-list-alt-action',</span>
<span class="linecomment">;;    `icicle-apropos-complete', `icicle-apropos-complete-and-exit',</span>
<span class="linecomment">;;    `icicle-apropos-complete-and-narrow',</span>
<span class="linecomment">;;    `icicle-apropos-complete-and-widen',</span>
<span class="linecomment">;;    `icicle-apropos-complete-no-display',</span>
<span class="linecomment">;;    `icicle-backward-delete-char-untabify',</span>
<span class="linecomment">;;    `icicle-backward-kill-paragraph',</span>
<span class="linecomment">;;    `icicle-backward-kill-sentence', `icicle-backward-kill-sexp',</span>
<span class="linecomment">;;    `icicle-backward-kill-word', `icicle-beginning-of-line+',</span>
<span class="linecomment">;;    `icicle-candidate-action', `icicle-candidate-alt-action',</span>
<span class="linecomment">;;    `icicle-candidate-read-fn-invoke',</span>
<span class="linecomment">;;    `icicle-candidate-set-complement',</span>
<span class="linecomment">;;    `icicle-candidate-set-define',</span>
<span class="linecomment">;;    `icicle-candidate-set-difference',</span>
<span class="linecomment">;;    `icicle-candidate-set-intersection',</span>
<span class="linecomment">;;    `icicle-candidate-set-retrieve',</span>
<span class="linecomment">;;    `icicle-candidate-set-retrieve-from-variable',</span>
<span class="linecomment">;;    `icicle-candidate-set-retrieve-more',</span>
<span class="linecomment">;;    `icicle-candidate-set-retrieve-persistent',</span>
<span class="linecomment">;;    `icicle-candidate-set-save', `icicle-candidate-set-save-more',</span>
<span class="linecomment">;;    `icicle-candidate-set-save-more-selected',</span>
<span class="linecomment">;;    `icicle-candidate-set-save-persistently',</span>
<span class="linecomment">;;    `icicle-candidate-set-save-selected',</span>
<span class="linecomment">;;    `icicle-candidate-set-save-to-variable',</span>
<span class="linecomment">;;    `icicle-candidate-set-swap', `icicle-candidate-set-truncate',</span>
<span class="linecomment">;;    `icicle-candidate-set-union',</span>
<span class="linecomment">;;    `icicle-change-alternative-sort-order',</span>
<span class="linecomment">;;    `icicle-change-sort-order', `icicle-choose-completion',</span>
<span class="linecomment">;;    `icicle-clear-current-history',</span>
<span class="linecomment">;;    `icicle-Completions-mouse-3-menu',</span>
<span class="linecomment">;;    `icicle-search-define-replacement',</span>
<span class="linecomment">;;    `icicle-delete-backward-char', `icicle-delete-candidate-object',</span>
<span class="linecomment">;;    `icicle-delete-char', `icicle-digit-argument',</span>
<span class="linecomment">;;    `icicle-dispatch-C-^', `icicle-dispatch-C-.',</span>
<span class="linecomment">;;    `icicle-dispatch-C-comma', `icicle-dispatch-M-comma',</span>
<span class="linecomment">;;    `icicle-dispatch-M-q', `icicle-doremi-candidate-width-factor',</span>
<span class="linecomment">;;    `icicle-doremi-inter-candidates-min-spaces',</span>
<span class="linecomment">;;    `icicle-end-of-line+', `icicle-erase-minibuffer',</span>
<span class="linecomment">;;    `icicle-erase-minibuffer-or-history-element',</span>
<span class="linecomment">;;    `icicle-exit-minibuffer', `icicle-goto/kill-failed-input',</span>
<span class="linecomment">;;    `icicle-help-on-candidate',</span>
<span class="linecomment">;;    `icicle-help-on-next-apropos-candidate',</span>
<span class="linecomment">;;    `icicle-help-on-next-prefix-candidate',</span>
<span class="linecomment">;;    `icicle-help-on-previous-apropos-candidate',</span>
<span class="linecomment">;;    `icicle-help-on-previous-prefix-candidate',</span>
<span class="linecomment">;;    `icicle-help-string-non-completion', `icicle-history',</span>
<span class="linecomment">;;    `icicle-insert-completion', `icicle-insert-history-element',</span>
<span class="linecomment">;;    `icicle-insert-key-description',</span>
<span class="linecomment">;;    `icicle-insert-list-join-string',</span>
<span class="linecomment">;;    `icicle-insert-newline-in-minibuffer',</span>
<span class="linecomment">;;    `icicle-insert-string-at-point',</span>
<span class="linecomment">;;    `icicle-insert-string-from-variable', `icicle-isearch-complete',</span>
<span class="linecomment">;;    `icicle-keep-only-past-inputs', `icicle-kill-line',</span>
<span class="linecomment">;;    `icicle-kill-paragraph', `icicle-kill-region',</span>
<span class="linecomment">;;    `icicle-kill-region-wimpy', `icicle-kill-sentence',</span>
<span class="linecomment">;;    `icicle-kill-sexp', `icicle-kill-word',</span>
<span class="linecomment">;;    `icicle-minibuffer-complete-and-exit', `icicle-minibuffer-help',</span>
<span class="linecomment">;;    `icicle-mouse-candidate-action',</span>
<span class="linecomment">;;    `icicle-mouse-candidate-alt-action',</span>
<span class="linecomment">;;    `icicle-mouse-candidate-read-fn-invoke',</span>
<span class="linecomment">;;    `icicle-mouse-candidate-set-save',</span>
<span class="linecomment">;;    `icicle-mouse-candidate-set-save-more',</span>
<span class="linecomment">;;    `icicle-mouse-choose-completion',</span>
<span class="linecomment">;;    `icicle-mouse-help-on-candidate',</span>
<span class="linecomment">;;    `icicle-mouse-remove-candidate',</span>
<span class="linecomment">;;    `icicle-mouse-save/unsave-candidate',</span>
<span class="linecomment">;;    `icicle-mouse-save-then-kill', `icicle-mouse-yank-secondary',</span>
<span class="linecomment">;;    `icicle-move-to-next-completion',</span>
<span class="linecomment">;;    `icicle-move-to-previous-completion',</span>
<span class="linecomment">;;    `icicle-narrow-candidates',</span>
<span class="linecomment">;;    `icicle-narrow-candidates-with-predicate',</span>
<span class="linecomment">;;    `icicle-negative-argument', `icicle-next-apropos-candidate',</span>
<span class="linecomment">;;    `icicle-next-apropos-candidate-action',</span>
<span class="linecomment">;;    `icicle-next-apropos-candidate-alt-action',</span>
<span class="linecomment">;;    `icicle-next-apropos-match-function',</span>
<span class="linecomment">;;    `icicle-next-candidate-per-mode',</span>
<span class="linecomment">;;    `icicle-next-candidate-per-mode-action', `icicle-next-line',</span>
<span class="linecomment">;;    `icicle-next-prefix-candidate',</span>
<span class="linecomment">;;    `icicle-next-prefix-candidate-action',</span>
<span class="linecomment">;;    `icicle-next-prefix-candidate-alt-action',</span>
<span class="linecomment">;;    `icicle-pp-eval-expression-in-minibuffer',</span>
<span class="linecomment">;;    `icicle-prefix-complete', `icicle-prefix-complete-no-display',</span>
<span class="linecomment">;;    `icicle-prefix-word-complete',</span>
<span class="linecomment">;;    `icicle-previous-apropos-candidate',</span>
<span class="linecomment">;;    `icicle-previous-apropos-candidate-action',</span>
<span class="linecomment">;;    `icicle-previous-apropos-candidate-alt-action',</span>
<span class="linecomment">;;    `icicle-previous-candidate-per-mode',</span>
<span class="linecomment">;;    `icicle-previous-candidate-per-mode-action',</span>
<span class="linecomment">;;    `icicle-previous-line', `icicle-previous-prefix-candidate',</span>
<span class="linecomment">;;    `icicle-previous-prefix-candidate-action',</span>
<span class="linecomment">;;    `icicle-previous-prefix-candidate-alt-action',</span>
<span class="linecomment">;;    `icicle-regexp-quote-input', `icicle-remove-candidate',</span>
<span class="linecomment">;;    `icicle-remove-Completions-window',</span>
<span class="linecomment">;;    `icicle-retrieve-last-input', `icicle-retrieve-next-input',</span>
<span class="linecomment">;;    `icicle-retrieve-previous-input', `icicle-reverse-sort-order',</span>
<span class="linecomment">;;    `icicle-save-predicate-to-variable',</span>
<span class="linecomment">;;    `icicle-save/unsave-candidate', `icicle-scroll-Completions',</span>
<span class="linecomment">;;    `icicle-scroll-Completions-up',</span>
<span class="linecomment">;;    `icicle-search-define-replacement', `icicle-self-insert',</span>
<span class="linecomment">;;    `icicle-sort-alphabetical', `icicle-sort-by-abbrev-frequency',</span>
<span class="linecomment">;;    `icicle-sort-by-directories-last',</span>
<span class="linecomment">;;    `icicle-sort-by-last-file-modification-time',</span>
<span class="linecomment">;;    `icicle-sort-by-last-use',</span>
<span class="linecomment">;;    `icicle-sort-by-previous-use-alphabetically',</span>
<span class="linecomment">;;    `icicle-sort-case-insensitive',</span>
<span class="linecomment">;;    `icicle-sort-proxy-candidates-first', `icicle-sort-turned-OFF',</span>
<span class="linecomment">;;    `icicle-switch-to-Completions-buf',</span>
<span class="linecomment">;;    `icicle-switch-to-completions',</span>
<span class="linecomment">;;    `icicle-switch-to/from-minibuffer',</span>
<span class="linecomment">;;    `icicle-toggle-~-for-home-dir', `icicle-toggle-C-for-actions',</span>
<span class="linecomment">;;    `icicle-toggle-alternative-sorting',</span>
<span class="linecomment">;;    `icicle-toggle-angle-brackets',</span>
<span class="linecomment">;;    `icicle-toggle-case-sensitivity',</span>
<span class="linecomment">;;    `icicle-toggle-expand-to-common-match',</span>
<span class="linecomment">;;    `icicle-toggle-fuzzy-completion',</span>
<span class="linecomment">;;    `icicle-toggle-highlight-all-current',</span>
<span class="linecomment">;;    `icicle-toggle-highlight-historical-candidates',</span>
<span class="linecomment">;;    `icicle-toggle-ignored-extensions',</span>
<span class="linecomment">;;    `icicle-toggle-ignored-space-prefix',</span>
<span class="linecomment">;;    `icicle-toggle-incremental-completion',</span>
<span class="linecomment">;;    `icicle-toggle-literal-replacement',</span>
<span class="linecomment">;;    `icicle-toggle-proxy-candidates', `icicle-toggle-regexp-quote',</span>
<span class="linecomment">;;    `icicle-toggle-search-cleanup',</span>
<span class="linecomment">;;    `icicle-toggle-search-replace-common-match',</span>
<span class="linecomment">;;    `icicle-toggle-search-replace-whole',</span>
<span class="linecomment">;;    `icicle-toggle-search-whole-word', `icicle-toggle-sorting',</span>
<span class="linecomment">;;    `icicle-toggle-transforming', `icicle-transpose-chars',</span>
<span class="linecomment">;;    `icicle-transpose-sexps', `icicle-transpose-words',</span>
<span class="linecomment">;;    `icicle-universal-argument', `icicle-universal-argument-minus',</span>
<span class="linecomment">;;    `icicle-universal-argument-more',</span>
<span class="linecomment">;;    `icicle-universal-argument-other-key', `icicle-up-directory',</span>
<span class="linecomment">;;    `icicle-widen-candidates', `icicle-yank', `icicle-yank-pop',</span>
<span class="linecomment">;;    `icicle-yank-secondary', `old-choose-completion',</span>
<span class="linecomment">;;    `old-exit-minibuffer', `old-minibuffer-complete-and-exit',</span>
<span class="linecomment">;;    `old-switch-to-completions', `toggle-icicle-~-for-home-dir',</span>
<span class="linecomment">;;    `toggle-icicle-C-for-actions',</span>
<span class="linecomment">;;    `toggle-icicle-alternative-sorting',</span>
<span class="linecomment">;;    `toggle-icicle-angle-brackets',</span>
<span class="linecomment">;;    `toggle-icicle-case-sensitivity',</span>
<span class="linecomment">;;    `toggle-icicle-expand-to-common-match',</span>
<span class="linecomment">;;    `toggle-icicle-fuzzy-completion',</span>
<span class="linecomment">;;    `toggle-icicle-highlight-all-current',</span>
<span class="linecomment">;;    `toggle-icicle-highlight-historical-candidates',</span>
<span class="linecomment">;;    `toggle-icicle-ignored-extensions',</span>
<span class="linecomment">;;    `toggle-icicle-ignored-space-prefix',</span>
<span class="linecomment">;;    `toggle-icicle-incremental-completion',</span>
<span class="linecomment">;;    `toggle-icicle-literal-replacement',</span>
<span class="linecomment">;;    `toggle-icicle-proxy-candidates', `toggle-icicle-regexp-quote',</span>
<span class="linecomment">;;    `toggle-icicle-search-cleanup',</span>
<span class="linecomment">;;    `toggle-icicle-search-replace-common-match',</span>
<span class="linecomment">;;    `toggle-icicle-search-replace-whole',</span>
<span class="linecomment">;;    `toggle-icicle-search-whole-word', `toggle-icicle-sorting',</span>
<span class="linecomment">;;    `toggle-icicle-transforming'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Faces defined in Icicles (in Custom group `icicles'):</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;    `icicle-candidate-part',</span>
<span class="linecomment">;;    `icicle-common-match-highlight-Completions',</span>
<span class="linecomment">;;    `icicle-complete-input', `icicle-completion',</span>
<span class="linecomment">;;    `icicle-Completions-instruction-1',</span>
<span class="linecomment">;;    `icicle-Completions-instruction-2',</span>
<span class="linecomment">;;    `icicle-current-candidate-highlight', `icicle-extra-candidate',</span>
<span class="linecomment">;;    `icicle-historical-candidate', `icicle-input-completion-fail',</span>
<span class="linecomment">;;    `icicle-input-completion-fail-lax',</span>
<span class="linecomment">;;    `icicle-match-highlight-Completions',</span>
<span class="linecomment">;;    `icicle-match-highlight-minibuffer',</span>
<span class="linecomment">;;    `icicle-mustmatch-completion', `icicle-proxy-candidate',</span>
<span class="linecomment">;;    `icicle-saved-candidate', `icicle-search-context-level-1',</span>
<span class="linecomment">;;    `icicle-search-context-level-2',</span>
<span class="linecomment">;;    `icicle-search-context-level-3',</span>
<span class="linecomment">;;    `icicle-search-context-level-4',</span>
<span class="linecomment">;;    `icicle-search-context-level-5',</span>
<span class="linecomment">;;    `icicle-search-context-level-6',</span>
<span class="linecomment">;;    `icicle-search-context-level-7',</span>
<span class="linecomment">;;    `icicle-search-context-level-8', `icicle-search-current-input',</span>
<span class="linecomment">;;    `icicle-search-main-regexp-current',</span>
<span class="linecomment">;;    `icicle-search-main-regexp-others', `icicle-special-candidate',</span>
<span class="linecomment">;;    `icicle-whitespace-highlight', `minibuffer-prompt'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  User options defined in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;    `icicle-act-before-cycle-flag', `icicle-add-buffer-name-flag',</span>
<span class="linecomment">;;    `icicle-add-proxy-candidates-flag',</span>
<span class="linecomment">;;    `icicle-alternative-sort-function',</span>
<span class="linecomment">;;    `icicle-anything-transform-candidates-flag',</span>
<span class="linecomment">;;    `icicle-apropos-complete-keys',</span>
<span class="linecomment">;;    `icicle-apropos-complete-no-display-keys',</span>
<span class="linecomment">;;    `icicle-apropos-cycle-next-keys',</span>
<span class="linecomment">;;    `icicle-apropos-cycle-next-action-keys',</span>
<span class="linecomment">;;    `icicle-apropos-cycle-previous-keys',</span>
<span class="linecomment">;;    `icicle-apropos-cycle-previous-action-keys',</span>
<span class="linecomment">;;    `icicle-apropos-match-fns-alist',</span>
<span class="linecomment">;;    `icicle-bookmark-name-length-max', `icicle-buffer-configs',</span>
<span class="linecomment">;;    `icicle-buffer-extras',</span>
<span class="linecomment">;;    `icicle-buffer-ignore-space-prefix-flag',</span>
<span class="linecomment">;;    `icicle-buffer-match-regexp', `icicle-buffer-no-match-regexp',</span>
<span class="linecomment">;;    `icicle-buffer-predicate', `icicle-buffer-require-match-flag'</span>
<span class="linecomment">;;    `icicle-buffer-sort', `icicle-candidate-width-factor',</span>
<span class="linecomment">;;    `icicle-change-region-background-flag',</span>
<span class="linecomment">;;    `icicle-change-sort-order-completion-flag',</span>
<span class="linecomment">;;    `icicle-C-l-uses-completion-flag', `icicle-color-themes',</span>
<span class="linecomment">;;    `icicle-comint-dynamic-complete-replacements',</span>
<span class="linecomment">;;    `icicle-command-abbrev-alist',</span>
<span class="linecomment">;;    `icicle-command-abbrev-match-all-parts-flag',</span>
<span class="linecomment">;;    `icicle-command-abbrev-priority-flag',</span>
<span class="linecomment">;;    `icicle-complete-key-anyway-flag',</span>
<span class="linecomment">;;    `icicle-complete-keys-self-insert-flag',</span>
<span class="linecomment">;;    `icicle-complete-on-demand-keys',</span>
<span class="linecomment">;;    `icicle-completion-history-max-length',</span>
<span class="linecomment">;;    `icicle-Completions-display-min-input-chars',</span>
<span class="linecomment">;;    `icicle-Completions-frame-at-right-flag',</span>
<span class="linecomment">;;    `icicle-Completions-window-max-height',</span>
<span class="linecomment">;;    `icicle-customize-save-flag',</span>
<span class="linecomment">;;    `icicle-customize-save-variable-function',</span>
<span class="linecomment">;;    `icicle-cycle-into-subdirs-flag',</span>
<span class="linecomment">;;    `icicle-cycling-respects-completion-mode',</span>
<span class="linecomment">;;    `icicle-default-thing-insertion', `icicle-default-value',</span>
<span class="linecomment">;;    `icicle-define-alias-commands-flag',</span>
<span class="linecomment">;;    `icicle-deletion-action-flag',</span>
<span class="linecomment">;;    `icicle-expand-input-to-common-match-flag',</span>
<span class="linecomment">;;    `icicle-file-extras', `icicle-file-match-regexp',</span>
<span class="linecomment">;;    `icicle-file-no-match-regexp', `icicle-file-predicate',</span>
<span class="linecomment">;;    `icicle-file-require-match-flag', `icicle-file-sort',</span>
<span class="linecomment">;;    `icicle-filesets-as-saved-completion-sets-flag',</span>
<span class="linecomment">;;    `icicle-fuzzy-completion-flag',</span>
<span class="linecomment">;;    `icicle-guess-cmds-in-path-flag',</span>
<span class="linecomment">;;    `icicle-hide-common-match-in-Completions-flag',</span>
<span class="linecomment">;;    `icicle-highlight-historical-candidates-flag',</span>
<span class="linecomment">;;    `icicle-highlight-input-completion-failure',</span>
<span class="linecomment">;;    `icicle-highlight-input-completion-failure-delay',</span>
<span class="linecomment">;;    `icicle-highlight-input-completion-failure-threshold',</span>
<span class="linecomment">;;    `icicle-highlight-input-initial-whitespace-flag',</span>
<span class="linecomment">;;    `icicle-highlight-lighter-flag',</span>
<span class="linecomment">;;    `icicle-ignore-space-prefix-flag',</span>
<span class="linecomment">;;    `icicle-incremental-completion-delay',</span>
<span class="linecomment">;;    `icicle-incremental-completion-flag',</span>
<span class="linecomment">;;    `icicle-incremental-completion-threshold',</span>
<span class="linecomment">;;    `icicle-inhibit-ding-flag', `icicle-input-string',</span>
<span class="linecomment">;;    `icicle-inter-candidates-min-spaces',</span>
<span class="linecomment">;;    `icicle-isearch-complete-keys', `icicle-key-complete-keys',</span>
<span class="linecomment">;;    `icicle-key-descriptions-use-&lt;&gt;-flag',</span>
<span class="linecomment">;;    `icicle-key-descriptions-use-angle-brackets-flag',</span>
<span class="linecomment">;;    `icicle-keymaps-for-key-completion', `icicle-kmacro-ring-max',</span>
<span class="linecomment">;;    `icicle-levenshtein-distance', `icicle-list-end-string',</span>
<span class="linecomment">;;    `icicle-list-join-string', `icicle-list-nth-parts-join-string',</span>
<span class="linecomment">;;    `icicle-mark-position-in-candidate',</span>
<span class="linecomment">;;    `icicle-minibuffer-setup-hook', `icicle-modal-cycle-down-keys',</span>
<span class="linecomment">;;    `icicle-modal-cycle-down-action-keys',</span>
<span class="linecomment">;;    `icicle-modal-cycle-up-keys',</span>
<span class="linecomment">;;    `icicle-modal-cycle-up-action-keys', `icicle-mode',</span>
<span class="linecomment">;;    `icicle-mode-hook', `icicle-option-type-prefix-arg-list',</span>
<span class="linecomment">;;    `icicle-point-position-in-candidate',</span>
<span class="linecomment">;;    `icicle-pp-eval-expression-print-length',</span>
<span class="linecomment">;;    `icicle-pp-eval-expression-print-level',</span>
<span class="linecomment">;;    `icicle-prefix-complete-keys',</span>
<span class="linecomment">;;    `icicle-prefix-complete-no-display-keys',</span>
<span class="linecomment">;;    `icicle-prefix-cycle-next-keys',</span>
<span class="linecomment">;;    `icicle-prefix-cycle-next-action-keys',</span>
<span class="linecomment">;;    `icicle-prefix-cycle-previous-keys',</span>
<span class="linecomment">;;    `icicle-prefix-cycle-previous-action-keys',</span>
<span class="linecomment">;;    `icicle-previous-candidate-keys',</span>
<span class="linecomment">;;    `icicle-redefine-standard-commands-flag',</span>
<span class="linecomment">;;    `icicle-regexp-quote-flag', `icicle-regexp-search-ring-max',</span>
<span class="linecomment">;;    `icicle-region-alist', `icicle-region-auto-open-files-flag',</span>
<span class="linecomment">;;    `icicle-region-background', `icicle-regions-name-length-max',</span>
<span class="linecomment">;;    `icicle-require-match-flag', `icicle-saved-completion-sets',</span>
<span class="linecomment">;;    `icicle-search-cleanup-flag',</span>
<span class="linecomment">;;    `icicle-search-context-match-predicate',</span>
<span class="linecomment">;;    `icicle-search-from-isearch-keys',</span>
<span class="linecomment">;;    `icicle-search-highlight-all-current-flag',</span>
<span class="linecomment">;;    `icicle-search-highlight-context-levels-flag',</span>
<span class="linecomment">;;    `icicle-search-highlight-threshold', `icicle-search-hook',</span>
<span class="linecomment">;;    `icicle-search-replace-common-match-flag',</span>
<span class="linecomment">;;    `icicle-search-replace-literally-flag',</span>
<span class="linecomment">;;    `icicle-search-replace-whole-candidate-flag',</span>
<span class="linecomment">;;    `icicle-search-ring-max', `icicle-search-whole-word-flag',</span>
<span class="linecomment">;;    `icicle-show-Completions-help-flag',</span>
<span class="linecomment">;;    `icicle-show-Completions-initially-flag',</span>
<span class="linecomment">;;    `icicle-sort-function', `icicle-sort-functions-alist',</span>
<span class="linecomment">;;    `icicle-special-candidate-regexp',</span>
<span class="linecomment">;;    `icicle-TAB-shows-candidates-flag',</span>
<span class="linecomment">;;    `icicle-test-for-remote-files-flag',</span>
<span class="linecomment">;;    `icicle-thing-at-point-functions',</span>
<span class="linecomment">;;    `icicle-top-level-key-bindings',</span>
<span class="linecomment">;;    `icicle-top-level-when-sole-completion-flag',</span>
<span class="linecomment">;;    `icicle-touche-pas-aux-menus-flag', `icicle-transform-function',</span>
<span class="linecomment">;;    `icicle-unpropertize-completion-result-flag',</span>
<span class="linecomment">;;    `icicle-update-input-hook', `icicle-use-~-for-home-dir-flag',</span>
<span class="linecomment">;;    `icicle-use-C-for-actions-flag',</span>
<span class="linecomment">;;    `icicle-use-candidates-only-once-flag',</span>
<span class="linecomment">;;    `icicle-word-completion-keys',</span>
<span class="linecomment">;;    `icicle-WYSIWYG-Completions-flag', `icicle-yank-function'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Non-interactive functions in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;    `custom-variable-p', `icicle-2nd-part-string-less-p',</span>
<span class="linecomment">;;    `icicle-abbreviate-or-expand-file-name', `icicle-activate-mark',</span>
<span class="linecomment">;;    `icicle-add-key+cmd', `icicle-all-candidates-action-1',</span>
<span class="linecomment">;;    `icicle-any-candidates-p', `icicle-anything-candidate-value',</span>
<span class="linecomment">;;    `icicle-apply-action', `icicle-apply-list-action',</span>
<span class="linecomment">;;    `icicle-apply-to-saved-candidate',</span>
<span class="linecomment">;;    `icicle-apropos-any-candidates-p',</span>
<span class="linecomment">;;    `icicle-apropos-any-file-name-candidates-p',</span>
<span class="linecomment">;;    `icicle-apropos-candidates', `icicle-apropos-complete-1',</span>
<span class="linecomment">;;    `icicle-barf-if-outside-Completions',</span>
<span class="linecomment">;;    `icicle-barf-if-outside-Completions-and-minibuffer',</span>
<span class="linecomment">;;    `icicle-barf-if-outside-minibuffer', `icicle-binary-option-p',</span>
<span class="linecomment">;;    `icicle-bind-completion-keys', `icicle-bind-isearch-keys',</span>
<span class="linecomment">;;    `icicle-bind-key-completion-keys-for-map-var',</span>
<span class="linecomment">;;    `icicle-bind-key-completion-keys-in-keymaps-from',</span>
<span class="linecomment">;;    `icicle-bind-other-keymap-keys',</span>
<span class="linecomment">;;    `icicle-bind-top-level-commands', `icicle-bookmark-cleanup',</span>
<span class="linecomment">;;    `icicle-bookmark-jump-1', `icicle-buffer-sort-*...*-last',</span>
<span class="linecomment">;;    `icicle-call-then-update-Completions',</span>
<span class="linecomment">;;    `icicle-cancel-Help-redirection', `icicle-candidate-action-1',</span>
<span class="linecomment">;;    `icicle-candidate-set-1', `icicle-candidate-set-retrieve-1',</span>
<span class="linecomment">;;    `icicle-candidate-set-save-1',</span>
<span class="linecomment">;;    `icicle-candidate-set-save-selected-1',</span>
<span class="linecomment">;;    `icicle-case-insensitive-string-less-p',</span>
<span class="linecomment">;;    `icicle-case-string-less-p', `icicle-cdr-lessp',</span>
<span class="linecomment">;;    `icicle-char-properties-in-buffer',</span>
<span class="linecomment">;;    `icicle-char-properties-in-buffers',</span>
<span class="linecomment">;;    `icicle-choose-anything-candidate',</span>
<span class="linecomment">;;    `icicle-choose-candidate-of-type',</span>
<span class="linecomment">;;    `icicle-choose-completion-string', `icicle-clear-history-1',</span>
<span class="linecomment">;;    `icicle-clear-history-entry', `icicle-clear-minibuffer',</span>
<span class="linecomment">;;    `icicle-color-blue-lessp', `icicle-color-green-lessp',</span>
<span class="linecomment">;;    `icicle-color-help', `icicle-color-hue-lessp',</span>
<span class="linecomment">;;    `icicle-color-red-lessp', `icicle-color-saturation-lessp',</span>
<span class="linecomment">;;    `icicle-color-value-lessp',</span>
<span class="linecomment">;;    `icicle-comint-dynamic-complete-as-filename',</span>
<span class="linecomment">;;    `icicle-comint-dynamic-simple-complete',</span>
<span class="linecomment">;;    `icicle-comint-hook-fn',</span>
<span class="linecomment">;;    `icicle-comint-replace-orig-completion-fns',</span>
<span class="linecomment">;;    `icicle-comint-search-get-final-choice',</span>
<span class="linecomment">;;    `icicle-comint-search-get-minibuffer-input',</span>
<span class="linecomment">;;    `icicle-comint-search-send-input',</span>
<span class="linecomment">;;    `icicle-command-abbrev-action', `icicle-command-abbrev-command',</span>
<span class="linecomment">;;    `icicle-command-abbrev-matching-commands',</span>
<span class="linecomment">;;    `icicle-command-abbrev-record', `icicle-command-abbrev-regexp',</span>
<span class="linecomment">;;    `icicle-command-abbrev-save',</span>
<span class="linecomment">;;    `icicle-command-abbrev-used-more-p',</span>
<span class="linecomment">;;    `icicle-command-names-alphabetic-p',</span>
<span class="linecomment">;;    `icicle-compilation-hook-fn',</span>
<span class="linecomment">;;    `icicle-compilation-search-in-context-fn',</span>
<span class="linecomment">;;    `icicle-complete-again-update', `icicle-complete-keys-1',</span>
<span class="linecomment">;;    `icicle-complete-keys-action', `icicle-completing-p',</span>
<span class="linecomment">;;    `icicle-completing-read', , `icicle-completing-read-multiple',</span>
<span class="linecomment">;;    `icicle-completing-read-history',</span>
<span class="linecomment">;;    `icicle-completion-all-completions',</span>
<span class="linecomment">;;    `icicle-completion-setup-function',</span>
<span class="linecomment">;;    `icicle-completion-try-completion',</span>
<span class="linecomment">;;    `icicle-current-completion-in-Completions',</span>
<span class="linecomment">;;    `icicle-current-sort-functions', `icicle-current-sort-order',</span>
<span class="linecomment">;;    `icicle-customize-faces', `icicle-custom-type',</span>
<span class="linecomment">;;    `icicle-dabbrev--abbrev-at-point',</span>
<span class="linecomment">;;    `icicle-define-crm-completion-map', ,</span>
<span class="linecomment">;;    `icicle-define-cycling-keys', `icicle-define-icicle-maps',</span>
<span class="linecomment">;;    `icicle-define-minibuffer-maps',</span>
<span class="linecomment">;;    `icicle-delete-candidate-object-1', `icicle-delete-count',</span>
<span class="linecomment">;;    `icicle-delete-current-candidate-object',</span>
<span class="linecomment">;;    `icicle-delete-file-or-directory',</span>
<span class="linecomment">;;    `icicle-delete-region-from-alist',</span>
<span class="linecomment">;;    `icicle-delete-whitespace-from-string',</span>
<span class="linecomment">;;    `icicle-describe-opt-action',</span>
<span class="linecomment">;;    `icicle-describe-opt-of-type-complete', `icicle-ding',</span>
<span class="linecomment">;;    `icicle-dired-read-shell-command',</span>
<span class="linecomment">;;    `icicle-dired-smart-shell-command', `icicle-dirs-last-p',</span>
<span class="linecomment">;;    `icicle-displayable-cand-from-saved-set',</span>
<span class="linecomment">;;    `icicle-display-cand-from-full-cand',</span>
<span class="linecomment">;;    `icicle-display-completion-list', `icicle-display-Completions',</span>
<span class="linecomment">;;    `icicle-display-candidates-in-Completions', `icicle-doc-action',</span>
<span class="linecomment">;;    `icicle-edmacro-parse-keys',</span>
<span class="linecomment">;;    `icicle-ensure-overriding-map-is-bound',</span>
<span class="linecomment">;;    `icicle-execute-extended-command-1',</span>
<span class="linecomment">;;    `icicle-expanded-common-match',</span>
<span class="linecomment">;;    `icicle-expanded-common-match-1', `icicle-expand-file-name',</span>
<span class="linecomment">;;    `icicle-explicit-saved-completion-candidates', `icicle-explore',</span>
<span class="linecomment">;;    `icicle-extra-candidates-first-p',</span>
<span class="linecomment">;;    `icicle-face-valid-attribute-values', `icicle-file-directory-p',</span>
<span class="linecomment">;;    `icicle-file-name-apropos-candidates',</span>
<span class="linecomment">;;    `icicle-file-name-directory-w-default',</span>
<span class="linecomment">;;    `icicle-file-name-input-p', `icicle-file-name-nondirectory',</span>
<span class="linecomment">;;    `icicle-file-name-prefix-candidates', `icicle-file-readable-p',</span>
<span class="linecomment">;;    `icicle-file-remote-p', `icicle-file-writable-p',</span>
<span class="linecomment">;;    `icicle-filesets-files-under', `icicle-files-within',</span>
<span class="linecomment">;;    `icicle-filter-alist', `icicle-filter-wo-input',</span>
<span class="linecomment">;;    `icicle-find-first-tag-action',</span>
<span class="linecomment">;;    `icicle-find-first-tag-other-window-action',</span>
<span class="linecomment">;;    `icicle-find-tag-action', `icicle-find-tag-define-candidates',</span>
<span class="linecomment">;;    `icicle-find-tag-define-candidates-1',</span>
<span class="linecomment">;;    `icicle-find-tag-final-act', `icicle-find-tag-help',</span>
<span class="linecomment">;;    `icicle-find-tag-quit-or-error',</span>
<span class="linecomment">;;    `icicle-first-matching-candidate',</span>
<span class="linecomment">;;    `icicle-fit-completions-window', `icicle-fix-default-directory',</span>
<span class="linecomment">;;    `icicle-flat-list', `icicle-font-name-history',</span>
<span class="linecomment">;;    `icicle-fn-doc-minus-sig', `icicle-frame-name-history',</span>
<span class="linecomment">;;    `icicle-frames-on', `icicle-function-name-history',</span>
<span class="linecomment">;;    `icicle-funvardoc-action', `icicle-fuzzy-candidates',</span>
<span class="linecomment">;;    `icicle-get-alist-candidate',</span>
<span class="linecomment">;;    `icicle-get-anything-actions-for-type',</span>
<span class="linecomment">;;    `icicle-get-anything-cached-candidates',</span>
<span class="linecomment">;;    `icicle-get-anything-candidates',</span>
<span class="linecomment">;;    `icicle-get-anything-candidates-of-type',</span>
<span class="linecomment">;;    `icicle-get-anything-default-actions-for-type',</span>
<span class="linecomment">;;    `icicle-get-anything-input-delay',</span>
<span class="linecomment">;;    `icicle-get-anything-req-pat-chars',</span>
<span class="linecomment">;;    `icicle-get-anything-types',</span>
<span class="linecomment">;;    `icicle-get-candidates-from-saved-set', `icicle-goto-marker-1',</span>
<span class="linecomment">;;    `icicle-goto-marker-1-action', `icicle-group-regexp',</span>
<span class="linecomment">;;    `icicle-dired-guess-shell-command',</span>
<span class="linecomment">;;    `icicle-help-on-candidate-symbol',</span>
<span class="linecomment">;;    `icicle-help-string-completion',</span>
<span class="linecomment">;;    `icicle-highlight-candidate-in-Completions',</span>
<span class="linecomment">;;    `icicle-highlight-complete-input',</span>
<span class="linecomment">;;    `icicle-highlight-initial-whitespace',</span>
<span class="linecomment">;;    `icicle-highlight-input-noncompletion',</span>
<span class="linecomment">;;    `icicle-highlight-input-noncompletion-rest',</span>
<span class="linecomment">;;    `icicle-highlight-lighter', `icicle-historical-alphabetic-p',</span>
<span class="linecomment">;;    `icicle-imenu-command-p', `icicle-imenu-in-buffer-p',</span>
<span class="linecomment">;;    `icicle-imenu-non-interactive-function-p',</span>
<span class="linecomment">;;    `icicle-increment-cand-nb+signal-end',</span>
<span class="linecomment">;;    `icicle-increment-color-hue', `icicle-increment-color-value',</span>
<span class="linecomment">;;    `icicle-Info-book-order-p',</span>
<span class="linecomment">;;    `icicle-Info-build-node-completions',</span>
<span class="linecomment">;;    `icicle-Info-build-node-completions-fix-*',</span>
<span class="linecomment">;;    `icicle-Info-goto-node-1', `icicle-Info-goto-node-action',</span>
<span class="linecomment">;;    `icicle-Info-index-action', `icicle-Info-read-node-name',</span>
<span class="linecomment">;;    `icicle-input-from-minibuffer', `icicle-insert-candidates',</span>
<span class="linecomment">;;    `icicle-insert-Completions-help-string',</span>
<span class="linecomment">;;    `icicle-insert-for-yank', `icicle-insert-input',</span>
<span class="linecomment">;;    `icicle-insert-thesaurus-entry-cand-fn', `icicle-insert-thing',</span>
<span class="linecomment">;;    `icicle-isearch-complete-past-string', `icicle-join-nth-parts',</span>
<span class="linecomment">;;    `icicle-key-description', `icicle-keys+cmds-w-prefix',</span>
<span class="linecomment">;;    `icicle-kill-a-buffer',</span>
<span class="linecomment">;;    `icicle-kill-a-buffer-and-update-completions',</span>
<span class="linecomment">;;    `icicle-kmacro-action', `icicle-last-modified-first-p',</span>
<span class="linecomment">;;    `icicle-levenshtein-match', `icicle-levenshtein-one-match',</span>
<span class="linecomment">;;    `icicle-levenshtein-one-regexp',</span>
<span class="linecomment">;;    `icicle-levenshtein-strict-match',</span>
<span class="linecomment">;;    `icicle-lisp-vanilla-completing-read',</span>
<span class="linecomment">;;    `icicle-make-color-candidate', `icicle-make-face-candidate',</span>
<span class="linecomment">;;    `icicle-make-frame-alist', `icicle-make-window-alist',</span>
<span class="linecomment">;;    `icicle-markers', `icicle-markers-to-readable',</span>
<span class="linecomment">;;    `icicle-marker+text',</span>
<span class="linecomment">;;    `icicle-maybe-multi-completion-completing-p',</span>
<span class="linecomment">;;    `icicle-maybe-sort-and-strip-candidates',`icicle-mctize-all',</span>
<span class="linecomment">;;    `icicle-mctized-display-candidate',</span>
<span class="linecomment">;;    `icicle-mctized-full-candidate', `icicle-minibuf-input',</span>
<span class="linecomment">;;    `icicle-minibuf-input-sans-dir', `icicle-minibuffer-prompt-end',</span>
<span class="linecomment">;;    `icicle-minibuffer-setup', `icicle-most-recent-first-p',</span>
<span class="linecomment">;;    `icicle-mouse-candidate-action-1',</span>
<span class="linecomment">;;    `icicle-msg-maybe-in-minibuffer', `icicle-ms-windows-NET-USE',</span>
<span class="linecomment">;;    `icicle-nb-of-candidate-in-Completions',</span>
<span class="linecomment">;;    `icicle-next-candidate',</span>
<span class="linecomment">;;    `icicle-next-single-char-property-change',</span>
<span class="linecomment">;;    `icicle-non-whitespace-string-p', `icicle-part-1-cdr-lessp',</span>
<span class="linecomment">;;    `icicle-part-1-lessp', `icicle-part-2-lessp',</span>
<span class="linecomment">;;    `icicle-part-3-lessp', `icicle-part-4-lessp',</span>
<span class="linecomment">;;    `icicle-part-N-lessp', `icicle-place-cursor',</span>
<span class="linecomment">;;    `icicle-place-overlay', `icicle-prefix-any-candidates-p',</span>
<span class="linecomment">;;    `icicle-prefix-any-file-name-candidates-p',</span>
<span class="linecomment">;;    `icicle-prefix-candidates', `icicle-prefix-complete-1',</span>
<span class="linecomment">;;    `icicle-prefix-keys-first-p', `icicle-proxy-candidate-first-p',</span>
<span class="linecomment">;;    `icicle-put-at-head', `icicle-put-whole-cand-prop',</span>
<span class="linecomment">;;    `icicle-raise-Completions-frame', `icicle-readable-to-markers',</span>
<span class="linecomment">;;    `icicle-read-char-exclusive', `icicle-read-face-name',</span>
<span class="linecomment">;;    `icicle-read-file-name', `icicle-read-from-minibuffer',</span>
<span class="linecomment">;;    `icicle-read-from-minibuf-nil-default',</span>
<span class="linecomment">;;    `icicle-read-single-key-description', `icicle-read-number',</span>
<span class="linecomment">;;    `icicle-read-shell-command',</span>
<span class="linecomment">;;    `icicle-read-shell-command-completing', `icicle-read-string',</span>
<span class="linecomment">;;    `icicle-read-string-completing',</span>
<span class="linecomment">;;    `icicle-read-var-value-satisfying', `icicle-rebind-global',</span>
<span class="linecomment">;;    `icicle-recompute-candidates',</span>
<span class="linecomment">;;    `icicle-redefine-standard-commands',</span>
<span class="linecomment">;;    `icicle-redefine-standard-options',</span>
<span class="linecomment">;;    `icicle-redefine-std-completion-fns',</span>
<span class="linecomment">;;    `icicle-region-add-buffers', `icicle-remap',</span>
<span class="linecomment">;;    `icicle-region-help', `icicle-region-or-buffer-limits',</span>
<span class="linecomment">;;    `icicle-region-sorted', `icicle-remove-buffer-candidate-action',</span>
<span class="linecomment">;;    `icicle-remove-buffer-config-action',</span>
<span class="linecomment">;;    `icicle-remove-cand-from-lists',</span>
<span class="linecomment">;;    `icicle-remove-candidate-display-others',</span>
<span class="linecomment">;;    `icicle-remove-color-duplicates', `icicle-remove-dots',</span>
<span class="linecomment">;;    `icicle-remove-duplicates', `icicle-remove-dups-if-extras',</span>
<span class="linecomment">;;    `icicle-remove-if', `icicle-remove-if-not',</span>
<span class="linecomment">;;    `icicle-remove-property', `icicle-remove-saved-set-action',</span>
<span class="linecomment">;;    `icicle-replace-input-w-parent-dir', `icicle-require-match-p',</span>
<span class="linecomment">;;    `icicle-restore-completion-keys',</span>
<span class="linecomment">;;    `icicle-restore-other-keymap-keys',</span>
<span class="linecomment">;;    `icicle-restore-region-face',</span>
<span class="linecomment">;;    `icicle-restore-standard-commands',</span>
<span class="linecomment">;;    `icicle-restore-standard-options',</span>
<span class="linecomment">;;    `icicle-restore-std-completion-fns',</span>
<span class="linecomment">;;    `icicle-retrieve-candidates-from-set', `icicle-reversible-sort',</span>
<span class="linecomment">;;    `icicle-run-icicle-post-command-hook',</span>
<span class="linecomment">;;    `icicle-run-icicle-pre-command-hook', `icicle-saved-fileset-p',</span>
<span class="linecomment">;;    `icicle-save-or-restore-input', `icicle-save-raw-input',</span>
<span class="linecomment">;;    `icicle-scatter', `icicle-scatter-match',</span>
<span class="linecomment">;;    `icicle-scroll-or-update-Completions', `icicle-search-action',</span>
<span class="linecomment">;;    `icicle-search-char-property-scan',</span>
<span class="linecomment">;;    `icicle-search-choose-buffers', `icicle-search-cleanup',</span>
<span class="linecomment">;;    `icicle-search-define-candidates',</span>
<span class="linecomment">;;    `icicle-search-define-candidates-1', `icicle-search-final-act',</span>
<span class="linecomment">;;    `icicle-search-help',</span>
<span class="linecomment">;;    `icicle-search-highlight-all-input-matches',</span>
<span class="linecomment">;;    `icicle-search-highlight-and-maybe-replace',</span>
<span class="linecomment">;;    `icicle-search-highlight-input-matches-here',</span>
<span class="linecomment">;;    `icicle-search-in-context-default-fn',</span>
<span class="linecomment">;;    `icicle-search-property-args', `icicle-search-quit-or-error',</span>
<span class="linecomment">;;    `icicle-search-read-context-regexp', `icicle-search-read-word',</span>
<span class="linecomment">;;    `icicle-search-regexp-scan', `icicle-search-region-action',</span>
<span class="linecomment">;;    `icicle-search-replace-candidate',</span>
<span class="linecomment">;;    `icicle-search-replace-fixed-case-p',</span>
<span class="linecomment">;;    `icicle-search-replace-match', `icicle-search-where-arg',</span>
<span class="linecomment">;;    `icicle-select-minibuffer-contents'</span>
<span class="linecomment">;;    `icicle-select-region-action', `icicle-set-calling-cmd',</span>
<span class="linecomment">;;    `icicle-set-difference', `icicle-set-intersection',</span>
<span class="linecomment">;;    `icicle-set-union', `icicle-shell-command',</span>
<span class="linecomment">;;    `icicle-shell-command-candidates',</span>
<span class="linecomment">;;    `icicle-shell-command-on-region',</span>
<span class="linecomment">;;    `icicle-shell-dynamic-complete-as-command',</span>
<span class="linecomment">;;    `icicle-shell-dynamic-complete-as-environment-variable',</span>
<span class="linecomment">;;    `icicle-signum', `icicle-S-iso-lefttab-to-S-TAB',</span>
<span class="linecomment">;;    `icicle-special-candidates-first-p',</span>
<span class="linecomment">;;    `icicle-start-of-candidates-in-Completions',</span>
<span class="linecomment">;;    `icicle-strip-ignored-files-and-sort',</span>
<span class="linecomment">;;    `icicle-subst-envvar-in-file-name',</span>
<span class="linecomment">;;    `icicle-substring-no-properties', `icicle-substrings-of-length',</span>
<span class="linecomment">;;    `icicle-successive-action', `icicle-this-command-keys-prefix',</span>
<span class="linecomment">;;    `icicle-top-level-prep', `icicle-transform-candidates',</span>
<span class="linecomment">;;    `icicle-transform-multi-completion',</span>
<span class="linecomment">;;    `icicle-transform-sole-candidate', `icicle-try-switch-buffer',</span>
<span class="linecomment">;;    `icicle-unbind-isearch-keys',</span>
<span class="linecomment">;;    `icicle-unbind-key-completion-keys-for-map-var',</span>
<span class="linecomment">;;    `icicle-unbind-key-completion-keys-in-keymaps-from',</span>
<span class="linecomment">;;    `icicle-undo-std-completion-faces',</span>
<span class="linecomment">;;    `icicle-unhighlight-lighter', `icicle-unmap',</span>
<span class="linecomment">;;    `icicle-unpropertize', `icicle-unsorted-apropos-candidates',</span>
<span class="linecomment">;;    `icicle-unsorted-file-name-apropos-candidates',</span>
<span class="linecomment">;;    `icicle-unsorted-file-name-prefix-candidates',</span>
<span class="linecomment">;;    `icicle-unsorted-prefix-candidates',</span>
<span class="linecomment">;;    `icicle-upcase-if-ignore-case', `icicle-update-and-next',</span>
<span class="linecomment">;;    `icicle-update-ignored-extensions-regexp',</span>
<span class="linecomment">;;    `icicle-value-satisfies-type-p', `icicle-var-inherits-type-p',</span>
<span class="linecomment">;;    `icicle-var-is-of-type-p', `icicle-var-matches-type-p',</span>
<span class="linecomment">;;    `icicle-var-val-satisfies-type-p',</span>
<span class="linecomment">;;    `old-choose-completion-string', `old-completing-read',</span>
<span class="linecomment">;;    `old-completing-read-multiple', `old-completion-setup-function',</span>
<span class="linecomment">;;    `old-dired-smart-shell-command', `old-display-completion-list',</span>
<span class="linecomment">;;    `old-face-valid-attribute-values', `old-read-face-name',</span>
<span class="linecomment">;;    `old-read-file-name', `old-read-from-minibuffer',</span>
<span class="linecomment">;;    `old-read-number', `old-read-string', `old-shell-command',</span>
<span class="linecomment">;;    `old-shell-command-on-region'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Internal variables defined in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;    `icicle-abs-file-candidates', `icicle-all-candidates-action-p',</span>
<span class="linecomment">;;    `icicle-all-candidates-list-action-fn',</span>
<span class="linecomment">;;    `icicle-all-candidates-list-alt-action-fn',</span>
<span class="linecomment">;;    `icicle-apply-nomsg', `icicle-apropos-complete-match-fn',</span>
<span class="linecomment">;;    `icicle-bookmark-history', `icicle-bookmark-menu-map',</span>
<span class="linecomment">;;    `icicle-buffer-config-history', `icicle-candidate-action-fn',</span>
<span class="linecomment">;;    `icicle-candidate-alt-action-fn', `icicle-candidate-entry-fn',</span>
<span class="linecomment">;;    `icicle-candidate-help-fn', `icicle-candidate-nb',</span>
<span class="linecomment">;;    `icicle-candidate-properties-alist', `icicle-candidates-alist',</span>
<span class="linecomment">;;    `icicle-char-property-value-history',</span>
<span class="linecomment">;;    `icicle-cmd-calling-for-completion', `icicle-color-history',</span>
<span class="linecomment">;;    `icicle-color-theme-history', `icicle-commands-for-abbrev',</span>
<span class="linecomment">;;    `icicle-common-match-string',</span>
<span class="linecomment">;;    `icicle-comp-base-is-default-dir-p',</span>
<span class="linecomment">;;    `icicle-complete-input-overlay', `icicle-complete-keys-alist',</span>
<span class="linecomment">;;    `icicle-complete-on-demand-cmd', `icicle-completing-p',</span>
<span class="linecomment">;;    `icicle-completion-candidates',</span>
<span class="linecomment">;;    `icicle-completion-prompt-overlay',</span>
<span class="linecomment">;;    `icicle-completion-set-history', `icicle-confirm-exit-commands',</span>
<span class="linecomment">;;    `icicle-crm-local-completion-map',</span>
<span class="linecomment">;;    `icicle-crm-local-must-match-map',</span>
<span class="linecomment">;;    `icicle-current-completion-candidate-overlay',</span>
<span class="linecomment">;;    `icicle-current-completion-mode', `icicle-current-input',</span>
<span class="linecomment">;;    `icicle-current-raw-input', `icicle-custom-menu-map',</span>
<span class="linecomment">;;    `icicle-cycling-p', `icicle-default-directory',</span>
<span class="linecomment">;;    `icicle-default-thing-insertion-flipped-p',</span>
<span class="linecomment">;;    `icicle-delete-candidate-object', `icicle-describe-menu-map',</span>
<span class="linecomment">;;    `icicle-dictionary-history', `icicle-dir-candidate-can-exit-p',</span>
<span class="linecomment">;;    `icicle-doc-last-initial-cand-set', `icicle-edit-menu-map',</span>
<span class="linecomment">;;    `icicle-edit-update-p', `icicle-explore-final-choice',</span>
<span class="linecomment">;;    `icicle-explore-final-choice-full', `icicle-extra-candidates',</span>
<span class="linecomment">;;    `icicle-extra-candidates-dir-insert-p',</span>
<span class="linecomment">;;    `icicle-face-name-history', `icicle-fancy-candidates-p',</span>
<span class="linecomment">;;    `icicle-fancy-cands-internal-p', `icicle-file-menu-map',</span>
<span class="linecomment">;;    `icicle-font-name-history', `icicle-frame-alist',</span>
<span class="linecomment">;;    `icicle-frame-name-history', `icicle-frames-menu-map',</span>
<span class="linecomment">;;    `icicle-function-name-history',</span>
<span class="linecomment">;;    `icicle-fundoc-last-initial-cand-set',</span>
<span class="linecomment">;;    `icicle-general-help-string', `icicle-ignored-extensions',</span>
<span class="linecomment">;;    `icicle-ignored-extensions-regexp',</span>
<span class="linecomment">;;    `icicle-incremental-completion-p', `icicle-info-menu-map',</span>
<span class="linecomment">;;    `icicle-Info-only-rest-of-book-p', `icicle-inhibit-sort-p',</span>
<span class="linecomment">;;    `icicle-inhibit-try-switch-buffer', `icicle-initial-value',</span>
<span class="linecomment">;;    `icicle-input-fail-pos', `icicle-insert-string-at-pt-end',</span>
<span class="linecomment">;;    `icicle-insert-string-at-pt-start', `icicle-kill-history',</span>
<span class="linecomment">;;    `icicle-kmacro-alist', `icicle-kmacro-history',</span>
<span class="linecomment">;;    `icicle-last-apropos-complete-match-fn',</span>
<span class="linecomment">;;    `icicle-last-completion-candidate',</span>
<span class="linecomment">;;    `icicle-last-completion-command', `icicle-last-input',</span>
<span class="linecomment">;;    `icicle-last-sort-function', `icicle-last-top-level-command',</span>
<span class="linecomment">;;    `icicle-last-transform-function', `icicle-list-use-nth-parts',</span>
<span class="linecomment">;;    `icicle-menu-map', `icicle-minor-mode-map-entry',</span>
<span class="linecomment">;;    `icicle-mode-map', `icicle-ms-windows-drive-hash',</span>
<span class="linecomment">;;    `icicle-must-match-regexp', `icicle-must-not-match-regexp',</span>
<span class="linecomment">;;    `icicle-must-pass-predicate',</span>
<span class="linecomment">;;    `icicle-nb-of-other-cycle-candidates',</span>
<span class="linecomment">;;    `icicle-next-apropos-complete-cycles-p',</span>
<span class="linecomment">;;    `icicle-next-prefix-complete-cycles-p',</span>
<span class="linecomment">;;    `icicle-object-named-types', `icicle-object-predicate-types',</span>
<span class="linecomment">;;    `icicle-old-read-file-name-fn', `icicle-options-menu-map',</span>
<span class="linecomment">;;    `icicle-plist-last-initial-cand-set',</span>
<span class="linecomment">;;    `icicle-pre-minibuffer-buffer', `icicle-post-command-hook',</span>
<span class="linecomment">;;    `icicle-pre-command-hook',</span>
<span class="linecomment">;;    `icicle-previous-raw-file-name-inputs',</span>
<span class="linecomment">;;    `icicle-previous-raw-non-file-name-inputs',</span>
<span class="linecomment">;;    `icicle-proxy-candidate-regexp', `icicle-proxy-candidates',</span>
<span class="linecomment">;;    `icicle-read-expression-map', `icicle-re-no-dot',</span>
<span class="linecomment">;;    `icicle-require-match-p', `icicle-respect-completion-styles-p',</span>
<span class="linecomment">;;    `icicle-reverse-sort-p', `icicle-saved-candidate-overlays',</span>
<span class="linecomment">;;    `icicle-saved-candidates-variables-obarray',</span>
<span class="linecomment">;;    `icicle-saved-completion-candidate',</span>
<span class="linecomment">;;    `icicle-saved-completion-candidates',</span>
<span class="linecomment">;;    `icicle-saved-completion-candidates-internal',</span>
<span class="linecomment">;;    `icicle-saved-ignored-extensions',</span>
<span class="linecomment">;;    `icicle-saved-kmacro-ring-max', `icicle-saved-proxy-candidates',</span>
<span class="linecomment">;;    `icicle-saved-regexp-search-ring-max',</span>
<span class="linecomment">;;    `icicle-saved-region-background',</span>
<span class="linecomment">;;    `icicle-saved-search-ring-max',</span>
<span class="linecomment">;;    `icicle-scroll-Completions-backward-p', `icicle-search-command',</span>
<span class="linecomment">;;    `icicle-search-context-level', `icicle-search-context-regexp',</span>
<span class="linecomment">;;    `icicle-search-current-overlay', `icicle-search-final-choice',</span>
<span class="linecomment">;;    `icicle-search-history', `icicle-search-in-context-fn',</span>
<span class="linecomment">;;    `icicle-searching-p', `icicle-search-level-overlays',</span>
<span class="linecomment">;;    `icicle-search-menu-map', `icicle-search-tags-menu-map',</span>
<span class="linecomment">;;    `icicle-search-overlays', `icicle-search-refined-overlays',</span>
<span class="linecomment">;;    `icicle-search-replacement',</span>
<span class="linecomment">;;    `icicle-search-replacement-history',</span>
<span class="linecomment">;;    `icicle-shell-command-candidates',</span>
<span class="linecomment">;;    `icicle-successive-grab-count',</span>
<span class="linecomment">;;    `icicle-text-property-value-history',</span>
<span class="linecomment">;;    `icicle-thing-at-pt-fns-pointer',</span>
<span class="linecomment">;;    `icicle-universal-argument-map',</span>
<span class="linecomment">;;    `icicle-vardoc-last-initial-cand-set',</span>
<span class="linecomment">;;    `icicle-vardoc-last-initial-option-cand-set',</span>
<span class="linecomment">;;    `icicle-variable-name-history',</span>
<span class="linecomment">;;    `icicle-whole-candidate-as-text-prop-p',</span>
<span class="linecomment">;;    `lacarte-menu-items-alist', `old-crm-local-completion-map',</span>
<span class="linecomment">;;    `old-crm-local-must-match-map'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Emacs functions defined in Icicles for older Emacs versions:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;    `select-frame-set-input-focus'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  Widgets (customization types) defined in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;    `icicle-key-definition'.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  ***** NOTE: These EMACS PRIMITIVES have been REDEFINED in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  `completing-read'              - (See below and doc string.)</span>
<span class="linecomment">;;  `display-completion-list'      - (See below and doc string.)</span>
<span class="linecomment">;;  `exit-minibuffer'              - Remove *Completion* window.</span>
<span class="linecomment">;;  `minibuffer-complete-and-exit' - Remove *Completion* window.</span>
<span class="linecomment">;;  `read-file-name'               - (See below and doc string.)</span>
<span class="linecomment">;;  `read-from-minibuffer'         - (See below and doc string.)</span>
<span class="linecomment">;;  `read-string'                  - (See below and doc string.)</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  ***** NOTE: The following functions defined in `dabbrev.el' have</span>
<span class="linecomment">;;              been REDEFINED in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  `dabbrev-completion' - Use Icicles completion when you repeat</span>
<span class="linecomment">;;                         (`C-M-/').</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  ***** NOTE: The following functions defined in `lisp.el' have</span>
<span class="linecomment">;;              been REDEFINED in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  `lisp-complete-symbol' - Selects *Completions* window even if on</span>
<span class="linecomment">;;                           another frame.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  ***** NOTE: The following functions defined in `mouse.el' have</span>
<span class="linecomment">;;              been REDEFINED in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  `mouse-choose-completion' - Return the number of the completion.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  ***** NOTE: The following functions defined in `simple.el' have</span>
<span class="linecomment">;;              been REDEFINED in Icicles:</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  `choose-completion-string' -</span>
<span class="linecomment">;;     Don't exit minibuffer after `lisp-complete-symbol' completion.</span>
<span class="linecomment">;;  `completion-setup-function' - 1. Put faces on inserted string(s).</span>
<span class="linecomment">;;                                2. Help on help.</span>
<span class="linecomment">;;  `switch-to-completions' - Always selects *Completions* window.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  `next-history-element' (advised only) -</span>
<span class="linecomment">;;     Depending on `icicle-default-value', select minibuffer</span>
<span class="linecomment">;;     contents.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  `repeat-complex-command' - Use `completing-read' to read command.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;  For descriptions of changes to this file, see `icicles-chg.el'.</span>
 
<span class="linecomment">;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;</span>
<span class="linecomment">;;</span>
<span class="linecomment">;; This program is free software; you can redistribute it and/or</span>
<span class="linecomment">;; modify it under the terms of the GNU General Public License as</span>
<span class="linecomment">;; published by the Free Software Foundation; either version 2, or (at</span>
<span class="linecomment">;; your option) any later version.</span>

<span class="linecomment">;; This program is distributed in the hope that it will be useful,</span>
<span class="linecomment">;; but WITHOUT ANY WARRANTY; without even the implied warranty of</span>
<span class="linecomment">;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the</span>
<span class="linecomment">;; GNU General Public License for more details.</span>

<span class="linecomment">;; You should have received a copy of the GNU General Public License</span>
<span class="linecomment">;; along with this program; see the file COPYING.  If not, write to</span>
<span class="linecomment">;; the Free Software Foundation, Inc., 51 Franklin Street, Fifth</span>
<span class="linecomment">;; Floor, Boston, MA 02110-1301, USA.</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;</span>
<span class="linecomment">;;</span>
<span class="linecomment">;;; Code:</span>

<span class="linecomment">;; Warn that Icicles is designed for use with a windowing system.</span>
(unless (or window-system (and (fboundp 'daemonp) (daemonp)))
  (with-output-to-temp-buffer "<span class="quote">*WARNING*</span>"
    (princ "<span class="quote">You might NOT want to use Icicles without a windowing </span>")
    (princ "<span class="quote">system (manager).\n\n</span>")
    (princ "<span class="quote">Consider using `emacsclient' (or `gnuclient').  </span>")
    (princ "<span class="quote">Icicles makes use of many\n</span>")
    (princ "<span class="quote">keys that are unavailable when running Emacs in console mode.  </span>")
    (princ "<span class="quote">If you do\n</span>")
    (princ "<span class="quote">use Icicles in this mode, you will want to rebind those keys - </span>")
    (princ "<span class="quote">see file\n`icicles-mode.el'.\n</span>"))
  (message "<span class="quote">*WARNING* - Icicles uses keys that require a windowing system</span>")
  (sit-for 5))

(eval-when-compile
 (when (&lt; emacs-major-version 20) (require 'cl))) <span class="linecomment">;; when, unless</span>

<span class="linecomment">;;;;;;;;;;;;;</span>


<span class="linecomment">;;; Load other Icicles files (except documentation) ------------------</span>

(require 'icicles-opt)
(require 'icicles-var)
(require 'icicles-face) <span class="linecomment">;; Requires opt</span>

(require 'icicles-fn) <span class="linecomment">;; Requires opt, var</span>
(require 'icicles-mac) <span class="linecomment">;; Requires var</span>
(require 'icicles-mcmd) <span class="linecomment">;; Requires opt, var, fn, mac</span>
(require 'icicles-cmd) <span class="linecomment">;; Requires mac, opt, var, fn, mcmd</span>
(require 'icicles-mode) <span class="linecomment">;; Requires opt, cmd</span>

<span class="linecomment">;;;;;;;;;;;;;;;;;;;;;;;</span>

(provide 'icicles)

<span class="linecomment">;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;</span>
<span class="linecomment">;;; icicles.el ends here</span></span></pre></div><div class="wrapper close"></div></div><div class="footer"><hr /><span class="gotobar bar"><a class="local" href="http://www.emacswiki.org/emacs/SiteMap">SiteMap</a> <a class="local" href="http://www.emacswiki.org/emacs/Search">Search</a> <a class="local" href="http://www.emacswiki.org/emacs/ElispArea">ElispArea</a> <a class="local" href="http://www.emacswiki.org/emacs/HowTo">HowTo</a> <a class="local" href="http://www.emacswiki.org/emacs/RecentChanges">RecentChanges</a> <a class="local" href="http://www.emacswiki.org/emacs/News">News</a> <a class="local" href="http://www.emacswiki.org/emacs/Problems">Problems</a> <a class="local" href="http://www.emacswiki.org/emacs/Suggestions">Suggestions</a> </span><span class="translation bar"><br />  <a class="translation new" rel="nofollow" href="http://www.emacswiki.org/emacs?action=translate;id=icicles.el;missing=de_es_fr_it_ja_ko_pt_ru_se_zh">Add Translation</a></span><span class="edit bar"><br /> <a class="edit" accesskey="e" title="Click to edit this page" rel="nofollow" href="http://www.emacswiki.org/emacs?action=edit;id=icicles.el">Edit this page</a> <a class="history" rel="nofollow" href="http://www.emacswiki.org/emacs?action=history;id=icicles.el">View other revisions</a> <a class="admin" rel="nofollow" href="http://www.emacswiki.org/emacs?action=admin;id=icicles.el">Administration</a></span><span class="time"><br /> Last edited 2009-02-24 00:44 UTC by <a class="author" title="from inet-nc01-o.oracle.com" href="http://www.emacswiki.org/emacs/DrewAdams">DrewAdams</a> <a class="diff" rel="nofollow" href="http://www.emacswiki.org/emacs?action=browse;diff=2;id=icicles.el">(diff)</a></span><div style="float:right; margin-left:1ex;">
<!-- Creative Commons License -->
<a href="http://creativecommons.org/licenses/GPL/2.0/"><img alt="CC-GNU GPL" style="border:none" src="/pics/cc-GPL-a.png" /></a>
<!-- /Creative Commons License -->
</div>

<!--
<rdf:RDF xmlns="http://web.resource.org/cc/"
 xmlns:dc="http://purl.org/dc/elements/1.1/"
 xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
<Work rdf:about="">
   <license rdf:resource="http://creativecommons.org/licenses/GPL/2.0/" />
  <dc:type rdf:resource="http://purl.org/dc/dcmitype/Software" />
</Work>

<License rdf:about="http://creativecommons.org/licenses/GPL/2.0/">
   <permits rdf:resource="http://web.resource.org/cc/Reproduction" />
   <permits rdf:resource="http://web.resource.org/cc/Distribution" />
   <requires rdf:resource="http://web.resource.org/cc/Notice" />
   <permits rdf:resource="http://web.resource.org/cc/DerivativeWorks" />
   <requires rdf:resource="http://web.resource.org/cc/ShareAlike" />
   <requires rdf:resource="http://web.resource.org/cc/SourceCode" />
</License>
</rdf:RDF>
-->

<p class="legal">
This work is licensed to you under version 2 of the
<a href="http://www.gnu.org/">GNU</a> <a href="/GPL">General Public License</a>.
Alternatively, you may choose to receive this work under any other
license that grants the right to use, copy, modify, and/or distribute
the work, as long as that license imposes the restriction that
derivative works have to grant the same rights and impose the same
restriction. For example, you may choose to receive this work under
the
<a href="http://www.gnu.org/">GNU</a>
<a href="/FDL">Free Documentation License</a>, the
<a href="http://creativecommons.org/">CreativeCommons</a>
<a href="http://creativecommons.org/licenses/sa/1.0/">ShareAlike</a>
License, the XEmacs manual license, or
<a href="/OLD">similar licenses</a>.
</p>
</div>
</body>
</html>
