(add-to-list 'load-path "~/.emacs.d/site-lisp/elib-1.0")
(add-to-list 'load-path "~/.emacs.d/site-lisp/cedet-1.0.1")
(add-to-list 'load-path "~/.emacs.d/site-lisp/cedet-1.0.1/common")
(load-file "~/.emacs.d/site-lisp/cedet-1.0.1/common/cedet.el")
(add-to-list 'load-path "~/.emacs.d/site-lisp/cedet-1.0.1/eieio")
(add-to-list 'load-path "~/.emacs.d/site-lisp/cedet-1.0.1/semantic")
(add-to-list 'load-path "~/.emacs.d/site-lisp/cedet-1.0.1/speedbar")
(add-to-list 'load-path "~/.emacs.d/site-lisp/jdee-2.4.0.1")
(add-to-list 'load-path "~/.emacs.d/site-lisp/jdee-2.4.0.1/lisp")
(require 'jde)
