language: emacs-lisp
env:
  - EMACS=emacs24         PATH="$HOME/.cask/bin:$PATH"

install:
  - sudo add-apt-repository -y ppa:cassou/emacs
  - sudo apt-get update -qq
  - sudo apt-get install -qq emacs24 emacs24-el
  - sudo apt-get install texinfo
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python

script:
  - make
  - make check
